// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tx.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	Msg           *anypb.Any             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature     *Signature             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	Time          uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Fee           uint64                 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Memo          string                 `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	NetworkId     uint64                 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	ChainId       uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"`       // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type MessageSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"`       // @gotags: json:"toAddress"
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// RegisterProtocol: a Nested Chain registers as a Lattice reputation source
type MessageRegisterProtocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminAddress  []byte                 `protobuf:"bytes,1,opt,name=admin_address,json=adminAddress,proto3" json:"adminAddress"` // @gotags: json:"adminAddress"
	ProtocolName  string                 `protobuf:"bytes,2,opt,name=protocol_name,json=protocolName,proto3" json:"protocolName"` // @gotags: json:"protocolName"
	ProtocolUrl   string                 `protobuf:"bytes,3,opt,name=protocol_url,json=protocolUrl,proto3" json:"protocolUrl"`    // @gotags: json:"protocolUrl"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRegisterProtocol) Reset() {
	*x = MessageRegisterProtocol{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRegisterProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRegisterProtocol) ProtoMessage() {}

func (x *MessageRegisterProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRegisterProtocol.ProtoReflect.Descriptor instead.
func (*MessageRegisterProtocol) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MessageRegisterProtocol) GetAdminAddress() []byte {
	if x != nil {
		return x.AdminAddress
	}
	return nil
}

func (x *MessageRegisterProtocol) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *MessageRegisterProtocol) GetProtocolUrl() string {
	if x != nil {
		return x.ProtocolUrl
	}
	return ""
}

// EmitReputationEvent: a registered protocol emits a reputation event for an address
type MessageEmitReputationEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolAddress []byte                 `protobuf:"bytes,1,opt,name=protocol_address,json=protocolAddress,proto3" json:"protocolAddress"` // @gotags: json:"protocolAddress"
	SubjectAddress  []byte                 `protobuf:"bytes,2,opt,name=subject_address,json=subjectAddress,proto3" json:"subjectAddress"`    // @gotags: json:"subjectAddress"
	EventType       string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"eventType"`                   // @gotags: json:"eventType"
	BasePoints      uint64                 `protobuf:"varint,4,opt,name=base_points,json=basePoints,proto3" json:"basePoints"`               // @gotags: json:"basePoints"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageEmitReputationEvent) Reset() {
	*x = MessageEmitReputationEvent{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEmitReputationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEmitReputationEvent) ProtoMessage() {}

func (x *MessageEmitReputationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEmitReputationEvent.ProtoReflect.Descriptor instead.
func (*MessageEmitReputationEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MessageEmitReputationEvent) GetProtocolAddress() []byte {
	if x != nil {
		return x.ProtocolAddress
	}
	return nil
}

func (x *MessageEmitReputationEvent) GetSubjectAddress() []byte {
	if x != nil {
		return x.SubjectAddress
	}
	return nil
}

func (x *MessageEmitReputationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MessageEmitReputationEvent) GetBasePoints() uint64 {
	if x != nil {
		return x.BasePoints
	}
	return 0
}

// FollowAddress: directed follow, no stake required
type MessageFollowAddress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FollowerAddress []byte                 `protobuf:"bytes,1,opt,name=follower_address,json=followerAddress,proto3" json:"followerAddress"` // @gotags: json:"followerAddress"
	TargetAddress   []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"`       // @gotags: json:"targetAddress"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageFollowAddress) Reset() {
	*x = MessageFollowAddress{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFollowAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFollowAddress) ProtoMessage() {}

func (x *MessageFollowAddress) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFollowAddress.ProtoReflect.Descriptor instead.
func (*MessageFollowAddress) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageFollowAddress) GetFollowerAddress() []byte {
	if x != nil {
		return x.FollowerAddress
	}
	return nil
}

func (x *MessageFollowAddress) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

// UnfollowAddress: remove a directed follow
type MessageUnfollowAddress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FollowerAddress []byte                 `protobuf:"bytes,1,opt,name=follower_address,json=followerAddress,proto3" json:"followerAddress"` // @gotags: json:"followerAddress"
	TargetAddress   []byte                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"targetAddress"`       // @gotags: json:"targetAddress"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageUnfollowAddress) Reset() {
	*x = MessageUnfollowAddress{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUnfollowAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnfollowAddress) ProtoMessage() {}

func (x *MessageUnfollowAddress) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnfollowAddress.ProtoReflect.Descriptor instead.
func (*MessageUnfollowAddress) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageUnfollowAddress) GetFollowerAddress() []byte {
	if x != nil {
		return x.FollowerAddress
	}
	return nil
}

func (x *MessageUnfollowAddress) GetTargetAddress() []byte {
	if x != nil {
		return x.TargetAddress
	}
	return nil
}

// EndorseAddress: staked endorsement, weight tied to endorser reputation score
type MessageEndorseAddress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EndorserAddress []byte                 `protobuf:"bytes,1,opt,name=endorser_address,json=endorserAddress,proto3" json:"endorserAddress"` // @gotags: json:"endorserAddress"
	SubjectAddress  []byte                 `protobuf:"bytes,2,opt,name=subject_address,json=subjectAddress,proto3" json:"subjectAddress"`    // @gotags: json:"subjectAddress"
	StakeAmount     uint64                 `protobuf:"varint,3,opt,name=stake_amount,json=stakeAmount,proto3" json:"stakeAmount"`            // @gotags: json:"stakeAmount"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageEndorseAddress) Reset() {
	*x = MessageEndorseAddress{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEndorseAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEndorseAddress) ProtoMessage() {}

func (x *MessageEndorseAddress) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEndorseAddress.ProtoReflect.Descriptor instead.
func (*MessageEndorseAddress) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageEndorseAddress) GetEndorserAddress() []byte {
	if x != nil {
		return x.EndorserAddress
	}
	return nil
}

func (x *MessageEndorseAddress) GetSubjectAddress() []byte {
	if x != nil {
		return x.SubjectAddress
	}
	return nil
}

func (x *MessageEndorseAddress) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

// RevokeEndorsement: unstake and remove an endorsement
type MessageRevokeEndorsement struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EndorserAddress []byte                 `protobuf:"bytes,1,opt,name=endorser_address,json=endorserAddress,proto3" json:"endorserAddress"` // @gotags: json:"endorserAddress"
	SubjectAddress  []byte                 `protobuf:"bytes,2,opt,name=subject_address,json=subjectAddress,proto3" json:"subjectAddress"`    // @gotags: json:"subjectAddress"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageRevokeEndorsement) Reset() {
	*x = MessageRevokeEndorsement{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRevokeEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRevokeEndorsement) ProtoMessage() {}

func (x *MessageRevokeEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRevokeEndorsement.ProtoReflect.Descriptor instead.
func (*MessageRevokeEndorsement) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MessageRevokeEndorsement) GetEndorserAddress() []byte {
	if x != nil {
		return x.EndorserAddress
	}
	return nil
}

func (x *MessageRevokeEndorsement) GetSubjectAddress() []byte {
	if x != nil {
		return x.SubjectAddress
	}
	return nil
}

// ReputationEvent: a single on-chain reputation signal
type ReputationEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolAddress []byte                 `protobuf:"bytes,1,opt,name=protocol_address,json=protocolAddress,proto3" json:"protocolAddress"` // @gotags: json:"protocolAddress"
	EventType       string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"eventType"`                   // @gotags: json:"eventType"
	BasePoints      uint64                 `protobuf:"varint,3,opt,name=base_points,json=basePoints,proto3" json:"basePoints"`               // @gotags: json:"basePoints"
	BlockHeight     uint64                 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"blockHeight"`            // @gotags: json:"blockHeight"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReputationEvent) Reset() {
	*x = ReputationEvent{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReputationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReputationEvent) ProtoMessage() {}

func (x *ReputationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReputationEvent.ProtoReflect.Descriptor instead.
func (*ReputationEvent) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *ReputationEvent) GetProtocolAddress() []byte {
	if x != nil {
		return x.ProtocolAddress
	}
	return nil
}

func (x *ReputationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ReputationEvent) GetBasePoints() uint64 {
	if x != nil {
		return x.BasePoints
	}
	return 0
}

func (x *ReputationEvent) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// Endorsement: a staked endorsement from one address to another
type Endorsement struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EndorserAddress       []byte                 `protobuf:"bytes,1,opt,name=endorser_address,json=endorserAddress,proto3" json:"endorserAddress"`                      // @gotags: json:"endorserAddress"
	StakeAmount           uint64                 `protobuf:"varint,2,opt,name=stake_amount,json=stakeAmount,proto3" json:"stakeAmount"`                                 // @gotags: json:"stakeAmount"
	EndorserScoreSnapshot uint64                 `protobuf:"varint,3,opt,name=endorser_score_snapshot,json=endorserScoreSnapshot,proto3" json:"endorserScoreSnapshot"` // @gotags: json:"endorserScoreSnapshot"
	BlockHeight           uint64                 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"blockHeight"`                                 // @gotags: json:"blockHeight"
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Endorsement) Reset() {
	*x = Endorsement{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorsement) ProtoMessage() {}

func (x *Endorsement) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorsement.ProtoReflect.Descriptor instead.
func (*Endorsement) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *Endorsement) GetEndorserAddress() []byte {
	if x != nil {
		return x.EndorserAddress
	}
	return nil
}

func (x *Endorsement) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *Endorsement) GetEndorserScoreSnapshot() uint64 {
	if x != nil {
		return x.EndorserScoreSnapshot
	}
	return 0
}

func (x *Endorsement) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// LatticeProfile: the full on-chain identity for an address
type LatticeProfile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RawScore             uint64                 `protobuf:"varint,2,opt,name=raw_score,json=rawScore,proto3" json:"rawScore"` // @gotags: json:"rawScore"
	Events               []*ReputationEvent     `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Followers            [][]byte               `protobuf:"bytes,4,rep,name=followers,proto3" json:"followers,omitempty"`
	Following            [][]byte               `protobuf:"bytes,5,rep,name=following,proto3" json:"following,omitempty"`
	EndorsementsReceived []*Endorsement         `protobuf:"bytes,6,rep,name=endorsements_received,json=endorsementsReceived,proto3" json:"endorsementsReceived"` // @gotags: json:"endorsementsReceived"
	Endorsing            [][]byte               `protobuf:"bytes,7,rep,name=endorsing,proto3" json:"endorsing,omitempty"`
	EndorsementStake     uint64                 `protobuf:"varint,8,opt,name=endorsement_stake,json=endorsementStake,proto3" json:"endorsementStake"` // @gotags: json:"endorsementStake"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LatticeProfile) Reset() {
	*x = LatticeProfile{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatticeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatticeProfile) ProtoMessage() {}

func (x *LatticeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatticeProfile.ProtoReflect.Descriptor instead.
func (*LatticeProfile) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *LatticeProfile) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *LatticeProfile) GetRawScore() uint64 {
	if x != nil {
		return x.RawScore
	}
	return 0
}

func (x *LatticeProfile) GetEvents() []*ReputationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *LatticeProfile) GetFollowers() [][]byte {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *LatticeProfile) GetFollowing() [][]byte {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *LatticeProfile) GetEndorsementsReceived() []*Endorsement {
	if x != nil {
		return x.EndorsementsReceived
	}
	return nil
}

func (x *LatticeProfile) GetEndorsing() [][]byte {
	if x != nil {
		return x.Endorsing
	}
	return nil
}

func (x *LatticeProfile) GetEndorsementStake() uint64 {
	if x != nil {
		return x.EndorsementStake
	}
	return 0
}

// Protocol: a registered Lattice protocol source
type Protocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminAddress  []byte                 `protobuf:"bytes,1,opt,name=admin_address,json=adminAddress,proto3" json:"adminAddress"` // @gotags: json:"adminAddress"
	ProtocolName  string                 `protobuf:"bytes,2,opt,name=protocol_name,json=protocolName,proto3" json:"protocolName"` // @gotags: json:"protocolName"
	ProtocolUrl   string                 `protobuf:"bytes,3,opt,name=protocol_url,json=protocolUrl,proto3" json:"protocolUrl"`    // @gotags: json:"protocolUrl"
	BlockHeight   uint64                 `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"blockHeight"`   // @gotags: json:"blockHeight"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Protocol) Reset() {
	*x = Protocol{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Protocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Protocol) ProtoMessage() {}

func (x *Protocol) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Protocol.ProtoReflect.Descriptor instead.
func (*Protocol) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *Protocol) GetAdminAddress() []byte {
	if x != nil {
		return x.AdminAddress
	}
	return nil
}

func (x *Protocol) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

func (x *Protocol) GetProtocolUrl() string {
	if x != nil {
		return x.ProtocolUrl
	}
	return ""
}

func (x *Protocol) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type FeeParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendFee       uint64                 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"` // @gotags: json:"sendFee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\x86\x01\n" +
	"\x17MessageRegisterProtocol\x12#\n" +
	"\radmin_address\x18\x01 \x01(\fR\fadminAddress\x12#\n" +
	"\rprotocol_name\x18\x02 \x01(\tR\fprotocolName\x12!\n" +
	"\fprotocol_url\x18\x03 \x01(\tR\vprotocolUrl\"\xb0\x01\n" +
	"\x1aMessageEmitReputationEvent\x12)\n" +
	"\x10protocol_address\x18\x01 \x01(\fR\x0fprotocolAddress\x12'\n" +
	"\x0fsubject_address\x18\x02 \x01(\fR\x0esubjectAddress\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vbase_points\x18\x04 \x01(\x04R\n" +
	"basePoints\"h\n" +
	"\x14MessageFollowAddress\x12)\n" +
	"\x10follower_address\x18\x01 \x01(\fR\x0ffollowerAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\"j\n" +
	"\x16MessageUnfollowAddress\x12)\n" +
	"\x10follower_address\x18\x01 \x01(\fR\x0ffollowerAddress\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\fR\rtargetAddress\"\x8e\x01\n" +
	"\x15MessageEndorseAddress\x12)\n" +
	"\x10endorser_address\x18\x01 \x01(\fR\x0fendorserAddress\x12'\n" +
	"\x0fsubject_address\x18\x02 \x01(\fR\x0esubjectAddress\x12!\n" +
	"\fstake_amount\x18\x03 \x01(\x04R\vstakeAmount\"n\n" +
	"\x18MessageRevokeEndorsement\x12)\n" +
	"\x10endorser_address\x18\x01 \x01(\fR\x0fendorserAddress\x12'\n" +
	"\x0fsubject_address\x18\x02 \x01(\fR\x0esubjectAddress\"\x9f\x01\n" +
	"\x0fReputationEvent\x12)\n" +
	"\x10protocol_address\x18\x01 \x01(\fR\x0fprotocolAddress\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vbase_points\x18\x03 \x01(\x04R\n" +
	"basePoints\x12!\n" +
	"\fblock_height\x18\x04 \x01(\x04R\vblockHeight\"\xb6\x01\n" +
	"\vEndorsement\x12)\n" +
	"\x10endorser_address\x18\x01 \x01(\fR\x0fendorserAddress\x12!\n" +
	"\fstake_amount\x18\x02 \x01(\x04R\vstakeAmount\x126\n" +
	"\x17endorser_score_snapshot\x18\x03 \x01(\x04R\x15endorserScoreSnapshot\x12!\n" +
	"\fblock_height\x18\x04 \x01(\x04R\vblockHeight\"\xc7\x02\n" +
	"\x0eLatticeProfile\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1b\n" +
	"\traw_score\x18\x02 \x01(\x04R\brawScore\x12.\n" +
	"\x06events\x18\x03 \x03(\v2\x16.types.ReputationEventR\x06events\x12\x1c\n" +
	"\tfollowers\x18\x04 \x03(\fR\tfollowers\x12\x1c\n" +
	"\tfollowing\x18\x05 \x03(\fR\tfollowing\x12G\n" +
	"\x15endorsements_received\x18\x06 \x03(\v2\x12.types.EndorsementR\x14endorsementsReceived\x12\x1c\n" +
	"\tendorsing\x18\a \x03(\fR\tendorsing\x12+\n" +
	"\x11endorsement_stake\x18\b \x01(\x04R\x10endorsementStake\"\x9a\x01\n" +
	"\bProtocol\x12#\n" +
	"\radmin_address\x18\x01 \x01(\fR\fadminAddress\x12#\n" +
	"\rprotocol_name\x18\x02 \x01(\tR\fprotocolName\x12!\n" +
	"\fprotocol_url\x18\x03 \x01(\tR\vprotocolUrl\x12!\n" +
	"\fblock_height\x18\x04 \x01(\x04R\vblockHeight\"&\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tx_proto_goTypes = []any{
	(*Transaction)(nil),                // 0: types.Transaction
	(*MessageSend)(nil),                // 1: types.MessageSend
	(*MessageRegisterProtocol)(nil),    // 2: types.MessageRegisterProtocol
	(*MessageEmitReputationEvent)(nil), // 3: types.MessageEmitReputationEvent
	(*MessageFollowAddress)(nil),       // 4: types.MessageFollowAddress
	(*MessageUnfollowAddress)(nil),     // 5: types.MessageUnfollowAddress
	(*MessageEndorseAddress)(nil),      // 6: types.MessageEndorseAddress
	(*MessageRevokeEndorsement)(nil),   // 7: types.MessageRevokeEndorsement
	(*ReputationEvent)(nil),            // 8: types.ReputationEvent
	(*Endorsement)(nil),                // 9: types.Endorsement
	(*LatticeProfile)(nil),             // 10: types.LatticeProfile
	(*Protocol)(nil),                   // 11: types.Protocol
	(*FeeParams)(nil),                  // 12: types.FeeParams
	(*Signature)(nil),                  // 13: types.Signature
	(*anypb.Any)(nil),                  // 14: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	14, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	13, // 1: types.Transaction.signature:type_name -> types.Signature
	8,  // 2: types.LatticeProfile.events:type_name -> types.ReputationEvent
	9,  // 3: types.LatticeProfile.endorsements_received:type_name -> types.Endorsement
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
